### ISSUE TITLE
pod failed to validate due to 1 error: ERROR | attributes: Missing required attribute `homepage`.

### ISSUE THREAD

**Issue by bsaritas** [firatsezel/react-native-check-accessibility#5]
**Environment:**
React Native version: 0.60

**Steps To Reproduce**
upgrade react native to 0.60.3
clean node modules and install it again
run pod install

**Required steps:**
podspec attributes must be corrected. It may be fetch from package.json.

**Comment by firatsezel** [comment]
fixed with commit bcf399ba39b1e2f2057420ab9e624361024ee403
