### ISSUE TITLE
Peer Dependency Error

### ISSUE THREAD

**Issue by hasretozkan** [firatsezel/react-native-check-accessibility#9]
Selamlar Fırat

Kütüphaneyi React Native 0.64 sürümüne yüklemek istediğimde aşağıdaki gibi bir sorunla karşılaştım. Force ile yükledim fakat ileride daha büyük sorunları olabilir diye düşündüm. Bir fikrin yada çözümün var ise yardımcı olursan sevinirim.

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: kocaeli@0.0.1
npm ERR! Found: react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-check-accessibility@1.1.8
npm ERR! node_modules/react-native-check-accessibility
npm ERR!   react-native-check-accessibility@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by firatsezel** [comment]
Selamlar Hasret,

Şu vakitler çok sıkışığım o yüzden hemen dönemedim. 0.64te daha denemedim kütüphaneyi. En kısa sürede çalıştırıp geri dönüş yapacağım.

**Comment by firatsezel** [comment]
Merhaba @hasretozkan 1.1.9 versiyonunu yayınladım. Kontrol edebilirsin.
